u-boot-imx-tools: set COMPATIBLE_MACHINE to "invalid"
When building an image that do not rely on meta-freescale (e.g
raspberrypi). The build fails due to a bad settings.

So we need to blacklist all machines so that we don't affect
external machines definition.

Fixes:

ERROR: Multiple .bb files are due to be built which each provide u-boot-tools-native:###########                                                                                             | ETA:  0:00:01
  virtual:native:/home/bdx-iot/koncepto/nxp/poky/meta/recipes-bsp/u-boot/u-boot-tools_2020.10.bb
  virtual:native:/home/bdx-iot/koncepto/nxp/meta-freescale/recipes-bsp/u-boot/u-boot-imx-tools_2020.04.bb
A list of tasks depending on these providers is shown and may help explain where the dependency comes from.
virtual:native:/home/bdx-iot/koncepto/nxp/poky/meta/recipes-bsp/u-boot/u-boot-tools_2020.10.bb has unique dependees:
...
ERROR: Multiple .bb files are due to be built which each provide u-boot-mkimage-native:
  virtual:native:/home/bdx-iot/koncepto/nxp/poky/meta/recipes-bsp/u-boot/u-boot-tools_2020.10.bb
  virtual:native:/home/bdx-iot/koncepto/nxp/meta-freescale/recipes-bsp/u-boot/u-boot-imx-tools_2020.04.bb
A list of tasks depending on these providers is shown and may help explain where the dependency comes from.
...
ERROR: Multiple .bb files are due to be built which each provide u-boot-mkenvimage-native:
  virtual:native:/home/bdx-iot/koncepto/nxp/poky/meta/recipes-bsp/u-boot/u-boot-tools_2020.10.bb
  virtual:native:/home/bdx-iot/koncepto/nxp/meta-freescale/recipes-bsp/u-boot/u-boot-imx-tools_2020.04.bb
A list of tasks depending on these providers is shown and may help explain where the dependency comes from.
virtual:native:/home/bdx-iot/koncepto/nxp/poky/meta/recipes-bsp/u-boot/u-boot-tools_2020.10.bb has unique dependees:
...

Signed-off-by: Pierre-Jean Texier <texier.pj2@gmail.com>